name: Integration

on: push

jobs:
  integration:
    runs-on: ubuntu-18.04
    container: python:3.8.11-slim

    steps:
    - name: Install container dependencies
      run: |
        apt-get update
        apt-get install -y make software-properties-common gnupg2 gcc
        add-apt-repository -y ppa:git-core/ppa
        apt-get install -y git
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install service dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install pipenv
        find /usr/lib -name "libffi.so*"
        ln -s /usr/lib/x86_64-linux-gnu/libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6
        make init
    - name: Run ci bundle command
      run: |
        make ci-bundle
